import moment from 'moment'


export const defaultValues = {
    task: {
        allowUserGroup: null,
        beginTime: moment().format('YYYY-MM-DD'),
        crc32: 0,
        createTime: moment().format('YYYY-MM-DD'),
        dayLimit: 0,
        dayTimes: 0,
        description: null,
        endTime: moment().format('YYYY-MM-DD'),
        flowType: 0,
        groupName: null,
        isDel: false,
        isEnabled: true,
        isNeedGet: false,
        name: '',
        operator: null,
        platformID: 0,
        point: 0,
        tagId: 0,
        taskButtonText: null,
        taskExpireDays: 100,
        taskID: null,
        taskIconUrl: null,
        taskMaxPoint: 0,
        taskMinPoint: 0,
        taskRewardType: 7,
        taskSort: 2,
        taskState: 1,
        taskStrategyID: null,
        taskSubType: 0,
        taskType: 5,
        taskUrl: null,
        totalLimit: 0,
        totalTimes: 0,
        updateTime: moment().format('YYYY-MM-DD')
    },

    gift: {
        activeName: null,
        amountLimit: 100,
        appLimit: null,
        beginTime: moment().format('YYYY-MM-DDT00:00:00'),
        chargeCode: null,
        companyId: null,
        consumeUrl: null,
        consumerCompanyId: null,
        crc32: -237252271,
        createTime: null,
        dayLimit: 100,
        dayTimes: 20,
        description: null,
        endTime: moment().format('YYYY-MM-DDTHH:mm:ss'),
        expireDay: 200,
        expireTime: moment().format('YYYY-MM-DDTHH:mm:ss'),
        giftId: null,
        giftReference: null,
        giftState: 2,
        giftTag: null,
        giftTagSort: 0,
        giftType: 1,
        giftValMax: 100,
        giftValMin: 10,
        giftValue: 50,
        iconUrl: null,
        isDel: false,
        isEnabled: true,
        isHomePageDisplay: false,
        isSupService: false,
        name: null,
        operator: null,
        payTypeLimit: 1,
        planAmount: null,
        planTimes: 0,
        platformID: 0,
        point: 1,
        remark: null,
        ruleUrl: null,
        shortDesc: null,
        supServiceName: null,
        supServiceSku: null,
        supportType: 1,
        totalLimit: 0,
        totalTimes: 0,
        updateTime: null,
        useAfterSend: false,
    }

}