export const taskConstants={
    
    CREATE_TASK:'CREATE_TASK',

    COMMIT_TASK:'COMMIT_TASK',

    COMMIT_TASK_TAG:'COMMIT_TASK_TAG',

    LOAD_TASK_LIST:'LOAD_TASK_LIST',

    LOAD_TASK_IN_LOCAL:'LOAD_TASK_IN_LOCAL',

    GET_TASK_TAGS:'GET_TASK_TAGS',

}